// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250426073346_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Knocked out a 5 km run before sunrise—felt great!",
                            Created = new DateTime(2025, 4, 16, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7442),
                            Title = "Morning Jog"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Sketching vs. wireframing takeaways from today’s class.",
                            Created = new DateTime(2025, 4, 18, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7648),
                            Title = "UX Lecture Notes"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Spilled latte on my keyboard; spent the afternoon cleaning switches.",
                            Created = new DateTime(2025, 4, 19, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7651),
                            Title = "Coffee Mishap"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Discovered brutalist websites—love the raw typography.",
                            Created = new DateTime(2025, 4, 20, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7654),
                            Title = "Design Inspiration"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Set up Trello and assigned tasks for the sociology presentation.",
                            Created = new DateTime(2025, 4, 22, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7656),
                            Title = "Group Project Sync"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Practiced persuasive speech; trimmed intro to stay under 7 minutes.",
                            Created = new DateTime(2025, 4, 23, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7659),
                            Title = "Public-Speaking Rehearsal"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Fixed the 500 error—missing header in the POST request.",
                            Created = new DateTime(2025, 4, 24, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7661),
                            Title = "API Breakthrough"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Refactored the diary search feature to use LINQ queries.",
                            Created = new DateTime(2025, 4, 25, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7663),
                            Title = "Late-Night Coding"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Listened to ‘Design Better’ while walking downtown.",
                            Created = new DateTime(2025, 4, 25, 21, 33, 46, 79, DateTimeKind.Local).AddTicks(7666),
                            Title = "Podcast Walk"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Demoed new UI to the client—positive feedback on the color palette.",
                            Created = new DateTime(2025, 4, 26, 3, 33, 46, 79, DateTimeKind.Local).AddTicks(7674),
                            Title = "Sprint Review"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
